### ISSUE TITLE
Build Failing with errors

### ISSUE THREAD

**Issue by scsijon** [protonesso/pkgutils#1]
Downloaded master 20190521

On one system it says it builds ok, but there is nothing in the 'command' files created.
In another (more up to date) system build is giving these errors >

# cd /mnt/sdb1/pkgutils-master
# make
g++ -DNDEBUG -std=c++11 -Os -Wall -pedantic -D_GNU_SOURCE -DVERSION=\"5.43.2\" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -MM main.cc pkgutil.cc pkgadd.cc pkgrm.cc pkginfo.cc > .depend
g++ -DNDEBUG -std=c++11 -Os -Wall -pedantic -D_GNU_SOURCE -DVERSION=\"5.43.2\" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -c -o main.o main.cc
In file included from /usr/include/c++/5/bits/basic_string.h:5249:0,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from main.cc:27:
/usr/include/c++/5/ext/string_conversions.h: In function ‘_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT*, _CharT**, _Base ...), const char*, const _CharT*, std::size_t*, _Base ...)’:
/usr/include/c++/5/ext/string_conversions.h:66:25: error: ‘ERANGE’ was not declared in this scope
       else if (errno == ERANGE
                         ^
In file included from /usr/include/c++/5/system_error:39:0,
                 from /usr/include/c++/5/bits/ios_base.h:46,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from main.cc:27:
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h: At global scope:
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:42:40: error: ‘EAFNOSUPPORT’ was not declared in this scope
       address_family_not_supported =   EAFNOSUPPORT,
                                        ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:43:28: error: ‘EADDRINUSE’ was not declared in this scope
       address_in_use =     EADDRINUSE,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:44:34: error: ‘EADDRNOTAVAIL’ was not declared in this scope
       address_not_available =    EADDRNOTAVAIL,
                                  ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:45:30: error: ‘EISCONN’ was not declared in this scope
       already_connected =    EISCONN,
                              ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:46:35: error: ‘E2BIG’ was not declared in this scope
       argument_list_too_long =    E2BIG,
                                   ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:47:35: error: ‘EDOM’ was not declared in this scope
       argument_out_of_domain =    EDOM,
                                   ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:48:25: error: ‘EFAULT’ was not declared in this scope
       bad_address =     EFAULT,
                         ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:49:32: error: ‘EBADF’ was not declared in this scope
       bad_file_descriptor =    EBADF,
                                ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:52:25: error: ‘EBADMSG’ was not declared in this scope
       bad_message =     EBADMSG,
                         ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:55:25: error: ‘EPIPE’ was not declared in this scope
       broken_pipe =     EPIPE,
                         ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:56:31: error: ‘ECONNABORTED’ was not declared in this scope
       connection_aborted =    ECONNABORTED,
                               ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:57:42: error: ‘EALREADY’ was not declared in this scope
       connection_already_in_progress =   EALREADY,
                                          ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:58:31: error: ‘ECONNREFUSED’ was not declared in this scope
       connection_refused =    ECONNREFUSED,
                               ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:59:29: error: ‘ECONNRESET’ was not declared in this scope
       connection_reset =    ECONNRESET,
                             ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:60:30: error: ‘EXDEV’ was not declared in this scope
       cross_device_link =    EXDEV,
                              ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:61:40: error: ‘EDESTADDRREQ’ was not declared in this scope
       destination_address_required =   EDESTADDRREQ,
                                        ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:62:35: error: ‘EBUSY’ was not declared in this scope
       device_or_resource_busy =   EBUSY,
                                   ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:63:32: error: ‘ENOTEMPTY’ was not declared in this scope
       directory_not_empty =    ENOTEMPTY,
                                ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:64:35: error: ‘ENOEXEC’ was not declared in this scope
       executable_format_error =   ENOEXEC,
                                   ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:65:32: error: ‘EEXIST’ was not declared in this scope
       file_exists =            EEXIST,
                                ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:66:28: error: ‘EFBIG’ was not declared in this scope
       file_too_large =     EFBIG,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:67:30: error: ‘ENAMETOOLONG’ was not declared in this scope
       filename_too_long =    ENAMETOOLONG,
                              ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:68:35: error: ‘ENOSYS’ was not declared in this scope
       function_not_supported =    ENOSYS,
                                   ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:69:29: error: ‘EHOSTUNREACH’ was not declared in this scope
       host_unreachable =    EHOSTUNREACH,
                             ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:72:31: error: ‘EIDRM’ was not declared in this scope
       identifier_removed =    EIDRM,
                               ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:75:34: error: ‘EILSEQ’ was not declared in this scope
       illegal_byte_sequence =    EILSEQ,
                                  ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:76:45: error: ‘ENOTTY’ was not declared in this scope
       inappropriate_io_control_operation =  ENOTTY,
                                             ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:77:25: error: ‘EINTR’ was not declared in this scope
       interrupted =     EINTR,
                         ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:78:29: error: ‘EINVAL’ was not declared in this scope
       invalid_argument =    EINVAL,
                             ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:79:26: error: ‘ESPIPE’ was not declared in this scope
       invalid_seek =     ESPIPE,
                          ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:80:22: error: ‘EIO’ was not declared in this scope
       io_error =     EIO,
                      ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:81:28: error: ‘EISDIR’ was not declared in this scope
       is_a_directory =     EISDIR,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:82:26: error: ‘EMSGSIZE’ was not declared in this scope
       message_size =     EMSGSIZE,
                          ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:83:26: error: ‘ENETDOWN’ was not declared in this scope
       network_down =     ENETDOWN,
                          ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:84:27: error: ‘ENETRESET’ was not declared in this scope
       network_reset =     ENETRESET,
                           ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:85:32: error: ‘ENETUNREACH’ was not declared in this scope
       network_unreachable =    ENETUNREACH,
                                ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:86:28: error: ‘ENOBUFS’ was not declared in this scope
       no_buffer_space =    ENOBUFS,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:87:29: error: ‘ECHILD’ was not declared in this scope
       no_child_process =    ECHILD,
                             ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:90:21: error: ‘ENOLINK’ was not declared in this scope
       no_link =     ENOLINK,
                     ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:93:30: error: ‘ENOLCK’ was not declared in this scope
       no_lock_available =    ENOLCK,
                              ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:96:33: error: ‘ENODATA’ was not declared in this scope
       no_message_available =    ENODATA, 
                                 ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:99:24: error: ‘ENOMSG’ was not declared in this scope
       no_message =     ENOMSG, 
                        ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:100:31: error: ‘ENOPROTOOPT’ was not declared in this scope
       no_protocol_option =    ENOPROTOOPT,
                               ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:101:31: error: ‘ENOSPC’ was not declared in this scope
       no_space_on_device =    ENOSPC,
                               ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:104:32: error: ‘ENOSR’ was not declared in this scope
       no_stream_resources =    ENOSR,
                                ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:107:37: error: ‘ENXIO’ was not declared in this scope
       no_such_device_or_address =   ENXIO,
                                     ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:108:28: error: ‘ENODEV’ was not declared in this scope
       no_such_device =     ENODEV,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:109:37: error: ‘ENOENT’ was not declared in this scope
       no_such_file_or_directory =   ENOENT,
                                     ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:110:28: error: ‘ESRCH’ was not declared in this scope
       no_such_process =    ESRCH,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:111:28: error: ‘ENOTDIR’ was not declared in this scope
       not_a_directory =    ENOTDIR,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:112:26: error: ‘ENOTSOCK’ was not declared in this scope
       not_a_socket =     ENOTSOCK,
                          ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:115:26: error: ‘ENOSTR’ was not declared in this scope
       not_a_stream =     ENOSTR,
                          ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:118:27: error: ‘ENOTCONN’ was not declared in this scope
       not_connected =     ENOTCONN,
                           ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:119:30: error: ‘ENOMEM’ was not declared in this scope
       not_enough_memory =    ENOMEM,
                              ^
In file included from /usr/include/errno.h:35:0,
                 from /usr/include/c++/5/cerrno:41,
                 from /usr/include/c++/5/ext/string_conversions.h:44,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from main.cc:27:
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:122:27: error: ‘EOPNOTSUPP’ was not declared in this scope
       not_supported =     ENOTSUP,
                           ^
In file included from /usr/include/c++/5/system_error:39:0,
                 from /usr/include/c++/5/bits/ios_base.h:46,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from main.cc:27:
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:129:34: error: ‘EINPROGRESS’ was not declared in this scope
       operation_in_progress =    EINPROGRESS,
                                  ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:130:35: error: ‘EPERM’ was not declared in this scope
       operation_not_permitted =   EPERM,
                                   ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:131:35: error: ‘EOPNOTSUPP’ was not declared in this scope
       operation_not_supported =   EOPNOTSUPP,
                                   ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:132:34: error: ‘EWOULDBLOCK’ was not declared in this scope
       operation_would_block =    EWOULDBLOCK,
                                  ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:138:30: error: ‘EACCES’ was not declared in this scope
       permission_denied =    EACCES,
                              ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:141:28: error: ‘EPROTO’ was not declared in this scope
       protocol_error =     EPROTO,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:144:35: error: ‘EPROTONOSUPPORT’ was not declared in this scope
       protocol_not_supported =    EPROTONOSUPPORT,
                                   ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:145:34: error: ‘EROFS’ was not declared in this scope
       read_only_file_system =    EROFS,
                                  ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:146:41: error: ‘EDEADLK’ was not declared in this scope
       resource_deadlock_would_occur =   EDEADLK,
                                         ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:147:42: error: ‘EAGAIN’ was not declared in this scope
       resource_unavailable_try_again =   EAGAIN,
                                          ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:148:32: error: ‘ERANGE’ was not declared in this scope
       result_out_of_range =    ERANGE,
                                ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:155:28: error: ‘ETIME’ was not declared in this scope
       stream_timeout =     ETIME,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:159:28: error: ‘ETXTBSY’ was not declared in this scope
       text_file_busy =     ETXTBSY,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:162:23: error: ‘ETIMEDOUT’ was not declared in this scope
       timed_out =     ETIMEDOUT,
                       ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:163:41: error: ‘ENFILE’ was not declared in this scope
       too_many_files_open_in_system =   ENFILE,
                                         ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:164:32: error: ‘EMFILE’ was not declared in this scope
       too_many_files_open =    EMFILE,
                                ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:165:28: error: ‘EMLINK’ was not declared in this scope
       too_many_links =     EMLINK,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:166:41: error: ‘ELOOP’ was not declared in this scope
       too_many_symbolic_link_levels =   ELOOP,
                                         ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:169:28: error: ‘EOVERFLOW’ was not declared in this scope
       value_too_large =    EOVERFLOW,
                            ^
/usr/include/x86_64-linux-gnu/c++/5/bits/error_constants.h:172:32: error: ‘EPROTOTYPE’ was not declared in this scope
       wrong_protocol_type =    EPROTOTYPE
                                ^
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 1
# 

Any ideas?

**Comment by protonesso** [comment]
What gcc version

**Comment by protonesso** [comment]
Anyway works fine with gcc 9

**Comment by scsijon** [comment]
depending on the system, it gcc5 on the Xenial and gcc6 on the Easy. I know their not the latest, but with linux there should be no need to update everything all the time.
I shall download the latest and try again, I have another I can use but as it's a test box, it's packages tend to get messed up and at present it needs rebuilding.

**Comment by scsijon** [comment]
Firstly, appologies with the time delay, I hadn't realized it was all the way back in May I last commented. I'm spending part of this weekend sorting out my github 'stuff' and have just got to your thread.
Anyway,
It eventually built with a gcc 8.3.0 system, but wasn't actually what I was at the time wanting, so put it on the backburner. I'm working on a toolchain at present towards musl/cclang/llvm and will look at this again when that is stable.

**Comment by protonesso** [comment]
@scsijon https://github.com/tpimh/ntgc

**Comment by scsijon** [comment]
thanks, I shall have a look at it.
